### ISSUE TITLE
How to toggle ?

### ISSUE THREAD

**Issue by ramstein74** [chriswessels/meteor-slideout#1]
hello, i cannot get it to toggle

can you post a simple "meteor" example ?

thank you

**Comment by chriswessels** [comment]
@ramstein74, see the Slideout API docs here: https://github.com/mango/slideout#api

When using meteor-slideout, instantiate the `slideout` object in a template onRendered callback like this: https://github.com/chriswessels/meteor-slideout#meteor-specific

Hope that helps.

Chris
