### ISSUE TITLE
Full working sample

### ISSUE THREAD

**Issue by daveeel** [chriswessels/meteor-slideout#2]
I dug a bit and can't get it to work. 
Is there a working sample for Meteor?

**Comment by damonmcminn** [comment]
Wasn't responding to touch events and `Slideout.enableTouch` undefined. Simplest solution was to manually bundle `slideout.min.js` in `client/lib` (to ensure `Slideout` is defined).

**Comment by chriswessels** [comment]
Hey @daveeel @damonmcminn,

It looks like the Slideout.js team have stopped tagging new releases on Github. This is problematic as it becomes difficult to track which version of their plugin is bundled in the smart package. I will continue to release new versions of this smart package, following the scheme: `SLIDEOUT-GITHUB-TAG`_`RELEASE-NUMBER-UNDER-THAT-TAG`.

The recently published `0.1.9_2` includes the latest code from the Slideout.js repo, so it should be exactly the same as bundling it yourself.

I've also published an example here: https://github.com/chriswessels/meteor-slideout/tree/master/example

Hope this helps!

Chris

**Comment by daveeel** [comment]
Thanks for the reply @chriswessels , though a bit late ;)
My colleague once told me it's the local / global variable issue, but I didn't look deeper since we've switched to Meteor + Polymer 1.0, which has a nice responsive drawer plus many goodies.

**Comment by damonmcminn** [comment]
Cheers Chris, especially for the example. Ta!
