### ISSUE TITLE
Not working in Chrome

### ISSUE THREAD

**Issue by joeydonuts** [chriswessels/meteor-slideout#6]
I have been using the slideout menu fro a while now.  However, it no longer works in chrome.  It works fine in Safari and Firefox and IE 11.  It worked in chrome at one time and I don't know exactly when it stopped working there.

I am using 51.0.2704.103 (64-bit) on OS X

I doesn't work in chrome on Android either.

**Comment by chriswessels** [comment]
I've just updated the package to include Slideout 0.1.12.

I hope that fixes it.
